# Generated by Django 5.1.4 on 2024-12-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='doctores',
            options={'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'verbose_name_plural': 'Historiales Médicos'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='reportes',
            options={'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
